/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmSettingsRouteImport } from './routes/crm.settings'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmBlogRouteImport } from './routes/crm.blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmBlogRoute = CrmBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => CrmRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benefits': typeof BenefitsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/blog': typeof CrmBlogRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benefits': typeof BenefitsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/blog': typeof CrmBlogRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm': typeof CrmIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benefits': typeof BenefitsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/blog': typeof CrmBlogRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benefits'
    | '/blog'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/crm/blog'
    | '/crm/contacts'
    | '/crm/pipeline'
    | '/crm/settings'
    | '/crm/'
    | '/api/public/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benefits'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/crm/blog'
    | '/crm/contacts'
    | '/crm/pipeline'
    | '/crm/settings'
    | '/crm'
    | '/api/public/chat'
  id:
    | '__root__'
    | '/'
    | '/benefits'
    | '/blog'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/crm/blog'
    | '/crm/contacts'
    | '/crm/pipeline'
    | '/crm/settings'
    | '/crm/'
    | '/api/public/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenefitsRoute: typeof BenefitsRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/blog': {
      id: '/crm/blog'
      path: '/blog'
      fullPath: '/crm/blog'
      preLoaderRoute: typeof CrmBlogRouteImport
      parentRoute: typeof CrmRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CrmRouteChildren {
  CrmBlogRoute: typeof CrmBlogRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmBlogRoute: CrmBlogRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmSettingsRoute: CrmSettingsRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenefitsRoute: BenefitsRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
